# Data Preprocessing
! As we are dealing with lots of data and that data is in raw form, before inputting that data
to machine learning algorithms, we need to convert it into meaningful data. This process
is called preprocessing the data. Scikit-learn has package named preprocessing for this
purpose. The preprocessing package has the following techniques:



# Binarisation 
for boolean result depend on threshold vlaue

In [18]:
import numpy as np
# import precessing pak from sklearn
from sklearn import preprocessing

Input_data = np.array(
 [

 [2.1, -1.9, 5.5],
 [-1.5, 2.4, 3.5],
 [0.5, -7.9, 5.6],
 [5.9, 2.3, -5.8]
 
 ])


 #binarized data ,threshol=.5
 #data above .5 will true

binarized_data=preprocessing.Binarizer(threshold=.5).transform(Input_data);

#output Binarized data
print(binarized_data)

[[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]


# Mean data
This technique is used to eliminate the mean from feature vector so that every feature
centered on zero.

# Standart deviation
Standard deviation is a measure of the amount of variation or dispersion in a set of values. It quantifies how much individual data points in a dataset differ from the mean (average) of the dataset. In other words, it provides a way to understand the spread or distribution of values in a dataset.


In [19]:
import numpy as np
from sklearn import preprocessing



Input_data = np.array([
    [2.1, -1.9, 5.5],
    [-1.5, 2.4, 3.5],
    [0.5, -7.9, 5.6],
    [5.9, 2.3, -5.8]])


'''
from numpy useing mean and std
axis=0 : mean of colum
axis=1 : mean of row'''

def  mean_std(input_data):
    # mean
    print("colum means : ",input_data.mean(axis=0))
    print("row means : ",input_data.mean(axis=1)) 


    # Standard deviation
    print("colum deviation : ",input_data.std(axis=0))
    print("row deviation : ",input_data.std(axis=1))



# find mean and std
mean_std(Input_data)








colum means :  [ 1.75  -1.275  2.2  ]
row means :  [ 1.9         1.46666667 -0.6         0.8       ]
colum deviation :  [2.71431391 4.20022321 4.69414529]
row deviation :  [3.02434566 2.14527905 5.56596802 4.89285193]


# Remove mean and std to make data cluster
using  Scale function

In [20]:
data_scaled=preprocessing.scale(Input_data)

"""find clustering data"""
mean_std(data_scaled)

colum means :  [1.11022302e-16 0.00000000e+00 0.00000000e+00]
row means :  [ 0.22771593 -0.01515392 -0.43783738  0.22527537]
colum deviation :  [1. 1. 1.]
row deviation :  [0.35469194 0.87086398 0.93976265 1.39215695]
