# Array Creation in Numpy

In [2]:
import numpy as np


"""create empty array"""
arr=np.empty(2,dtype=int)
print(arr)

[-9093133594791772939      140565675065240]


In [ ]:
"""  2d  array"""

arr=np.empty([2,2],dtype=int)
print(arr)


### Zeros method

In [13]:
# zeros method:

arr=np.zeros(2)
print(arr)

# ndm
arr=np.zeros([10,10])
print(arr)

[0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Arrange method

In [37]:

#arrange with value 0->n

print(" 0 -> n : ")
arr=np.arange(10)
print(arr,"\n")


# value: x->y
print("x -> y : ")
arr=np.arange(10,20)
print(arr,"\n")


# value: x ->y increasing inteval
print("x -> y incresing interval : ")
arr=np.arange(10,100,10)
print(arr,'\n')

print("Reshape data : ")
arr=np.arange(10).reshape(2,5)
print(arr,'\n')



# constract 3D array
print()
arr=np.arange(24).reshape(2,3,4)
print(arr)

 0 -> n : 
[0 1 2 3 4 5 6 7 8 9] 

x -> y : 
[10 11 12 13 14 15 16 17 18 19] 

x -> y incresing interval : 
[10 20 30 40 50 60 70 80 90] 

Reshape data : 
[[0 1 2 3 4]
 [5 6 7 8 9]] 


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### LineSpace method


In [55]:
# divide xy interval in specific equal position
arr=np.linspace(1,4,6)
print("divide data : ",arr,"\n"*2)

# make arr vlaue sin
print("sin value : " ,np.sin(arr),"\n"*2)




divide data :  [1.  1.6 2.2 2.8 3.4 4. ] 


sin value :  [ 0.84147098  0.9995736   0.8084964   0.33498815 -0.2555411  -0.7568025 ] 




### Flatten mathod
use for combine  nd array in 1d array

In [47]:
arr=np.array([[1,2,3],[4,5,6]])



#row flatten
print("Raw flatten   :  ",arr.flatten())
print("Colum flatten :  ",arr.flatten('F'),'\n')

Raw flatten   :   [1 2 3 4 5 6]
Colum flatten :   [1 4 2 5 3 6] 



### ones method


In [49]:
arr= np.ones((10,10))
print("all one : \n",arr,"\n"*2)




all one : 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] 




### Eye() :
* make diagonal array

In [68]:
arr=np.eye(4,4, dtype=int,)
print(arr,"\n"*2)


arr=np.eye(4,4, dtype=int,k=-1)
print("remove first diagonal : \n",arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] 


remove first diagonal : 
 [[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


### Full(): 
creat a full array with a value


In [69]:
arr=np.full([2,4],3)
print(arr)

[[3 3 3 3]
 [3 3 3 3]]


### FromReconds()
use for make recond

In [74]:
arr=np.core.records.fromrecords(
  [["Mizan ",21,400000],
    ["sizan",22,80000],
    ["karim ",201,4000]], names='Name,age,salary'
)


print(arr.Name)
print(arr.age)
print(arr.salary)
print(arr)

['Mizan ' 'sizan' 'karim ']
[ 21  22 201]
[400000  80000   4000]
[('Mizan ',  21, 400000) ('sizan',  22,  80000) ('karim ', 201,   4000)]
